pool:
  vmImage: 'windows-2019'
steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '12.x'
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target Build-CI'
